{
 "title": "Heating Optimization",
 "time": { "from": "2023-12-31T23:00:00.000Z", "to": "2024-12-31T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "Scenario",
    "query": "SELECT name FROM public.optimization_result\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Hood Energy demand",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select total_energy_demand\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Full Load Hours without Electric Heating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select full_load_hours\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Full Load Hours with Electric Heating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select full_load_hours_after_optimization\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Gas Used for Heating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select gas_usage\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Electricity Used for Heating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select electricity_used\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Emissions Savings by Using Hybrid Electric Heating vs. just Gas Heating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select emissions_savings\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Cost Savings by Using Hybrid Electric Heating vs. just Gas Heating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select cost_savings\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Ratio Electric Heating in Low Price Windows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select electric_heating_in_low_price_windows_ratio\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Mean Electricity Price When Heating",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select mean_electricity_price_when_heating\nFROM optimization_result WHERE name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Mean Gas Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select avg(price)\nFROM prices WHERE source = 'gas_spot'"
    }
   ]
  },
  {
   "title": "Mean Electricity Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select avg(price)\nFROM prices WHERE source = 'smard'"
    }
   ]
  },
  {
   "title": "Usage of Electric Heaters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT \n    $__timeGroupAlias(timestamp, $__interval),\n    (electricity_used) AS \"Electric Heaters\"\nFROM \n    flexible_power\nWHERE \n    $__timeFilter(\"timestamp\")\n    AND optimization_case_name = '$Scenario'"
    }
   ]
  },
  {
   "title": "Heat Demand of the Hood",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "rawSql": "SELECT \n    $__timeGroupAlias(timestamp, $__interval),\n    (value*4) AS \"Heat Demand\"\nFROM \n    simulation_input_data \nWHERE \n    $__timeFilter(\"timestamp\")\n    AND name = 'flexible_device_demand'"
    }
   ]
  },
  {
   "title": "Co2 vs Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "rawSql": "SELECT \n    $__timeGroupAlias(timestamp, $__interval),\n    co2 AS \"Grid Co2 intensity\"\nFROM \n    footprint \nWHERE \n    $__timeFilter(\"timestamp\")\n"
    },
    {
     "rawSql": "SELECT \n    $__timeGroupAlias(timestamp, $__interval),\n    (price) AS \"Price\"\nFROM \n    prices \nWHERE \n    $__timeFilter(\"timestamp\") AND source = 'smard'\n"
    },
    {
     "rawSql": "SELECT\n  date_trunc('minute', timestamp) AS time,\n  COALESCE(\n    MAX(\n      CASE WHEN low_price_window = 1 THEN 1 ELSE 0 END\n    ), 0\n  ) AS \"Low Price Window\"\nFROM\n  flexible_power\nWHERE\n  optimization_case_name = '$Scenario'\nGROUP BY\n  time\nORDER BY\n  time\n"
    }
   ]
  }
 ]
}