{
 "title": "smard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stromerzeugung SMARD (average over ${__interval})",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"timestamp\",$__interval),\n  \"commodity_name\" AS metric,\n  avg(\"mwh\"*4) AS \"mwh\"\nFROM\n  grid\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY 1,2\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT \n    $__timeGroupAlias(timestamp, $__interval),\n    co2 AS \"Co2 intensity\"\nFROM \n    footprint \nWHERE \n    $__timeFilter(\"timestamp\")\n"
    }
   ]
  },
  {
   "title": "Energy demand PM1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT \n    $__timeGroupAlias(timestamp, $__interval),\n    heat_demand AS \"Thermal Energy\"\nFROM \n    process_heat\nWHERE \n    $__timeFilter(\"timestamp\")\n"
    },
    {
     "rawSql": "SELECT \n    $__timeGroupAlias(timestamp, $__interval),\n    power_demand AS \"Electricity\"\nFROM \n    process_electricity \nWHERE \n    $__timeFilter(\"timestamp\")\n"
    }
   ]
  },
  {
   "title": "Consumed Electricity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(power_demand * (5.0 / 3600.0)) AS \"Total Energy Consumed (Wh)\"\nFROM \n    process_electricity \n"
    }
   ]
  },
  {
   "title": "Consumed Thermal Energy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(heat_demand * (5.0 / 3600.0)) AS \"Total Energy Consumed (Wh)\"\nFROM \n    process_heat \n"
    }
   ]
  }
 ]
}